### ISSUE TITLE
Request to be added topics

### ISSUE THREAD

**Issue by switschel** [elpinjo/CumulocityClient#4]
Hi Misja,

can you add the 'cumulocity-iot' topic so your repo can be more easier found by others?
Also can you add one or multiple of the following topics so we can categorize your repos?

'agent' or 'cumulocity-agent'
'webapp' or 'cumulocity-webapp'
'widget' or 'cumulocity-widget'
'client' or 'cumulocity-client'
'cli' or 'cumulocity-cli'
'microservice' or 'cumulocity-microservice'
'example' or 'cumulocity-example'
'tutorial' or 'cumulocity-tutorial'
'simulator' or 'cumulocity-simulator'
'extension' or 'cumulocity-extension'

Thanks & Regards
Stefan

**Comment by elpinjo** [comment]
topics have been added to the repository
