### ISSUE TITLE
Operations

### ISSUE THREAD

**Issue by josaban** [elpinjo/CumulocityClient#5]
Please, can you give us example how you wrote operation to be executed?

**Comment by elpinjo** [comment]
Good Idea. I will add an example.

**Comment by elpinjo** [comment]
I just checked the code. There already is an example called ControlLed. 
As you can see in the example we set the Relay operation: 

`c8yClient.setSupportedOperations("c8y_Relay,c8y_Command,c8y_Restart");`

we registered the callback routine that processes the commands coming from Cumulocity to this device:

`c8yClient.setCallback(switchLed);`

And the switchLed function will turn on the built-in led or turn it off when the relay state is changed.

To test this out one can create a dashboard for the device and add the relay widget on the dashboard to switch the built-in led on or off. 

I hope this helps.

**Comment by josaban** [comment]
Dear,

I apologize if the issue on GitHub was unnecessary. I'm new to this, so perhaps I don't understand the system well enough and how everything functions. I communicate via NB and MQTT with a platform in Croatia that is based on Cumulocity. I successfully registered the device, sent some measurements, and activated an alarm, but I'm unable to perform any operation when the alarm is triggered. I'm unclear about the payload system when creating an operation to be executed on the platform.

Best regards,
Josip Sabic
________________________________
Šalje: Misja Heuveling ***@***.***>
Poslano: 23. svibnja 2023. 10:00
Prima: elpinjo/CumulocityClient ***@***.***>
Kopija: Josip Šabić ***@***.***>; Author ***@***.***>
Predmet: Re: [elpinjo/CumulocityClient] Operations (Issue #5)


I just checked the code. There already is an example called ControlLed.
As you can see in the example we set the Relay operation:

c8yClient.setSupportedOperations("c8y_Relay,c8y_Command,c8y_Restart");

we registered the callback routine that processes the commands coming from Cumulocity to this device:

c8yClient.setCallback(switchLed);

And the switchLed function will turn on the built-in led or turn it off when the relay state is changed.

To test this out one can create a dashboard for the device and add the relay widget on the dashboard to switch the built-in led on or off.

I hope this helps.

**Comment by elpinjo** [comment]
Hi Josip,

One thing to know is that the datamodel of Cumulocity is very flexible. There are a few predefined operations like c8y_Restart and c8y_Relay. And example of the c8y_Relay command is as follows:

```
{
    "description": "Turn on Led",
    "c8y_Relay": {
        "relayState": "CLOSED"
    }
}
```

So to execute an operation upon an alarm go to smart rules and create a new smartrule to create an operation upon an alarm:

![image](https://github.com/elpinjo/CumulocityClient/assets/4513460/eecbbad6-1961-4dd1-a09d-8fceb6cdccc3)

Next fill in the fields with the content like so:

![image](https://github.com/elpinjo/CumulocityClient/assets/4513460/889e8360-6a41-4f80-9497-671408c5cc94)

For custom operations, you need to supply a description and replace the "c8y_Relay" object in the JSON code with anything you like to put there. In the arduino code you can check the content of this to determine what to do and what parameters to use if provided. 

Also remind yourself that an operation has 3 statusses and you will have to update them. These are Sent, Pending and completed. For more information checkout the documentation: https://cumulocity.com/guides/concepts/domain-model/#operations

The API documentation also gives quite a good introduction: https://cumulocity.com/guides/device-integration/rest/

And a final pointer to the MQTT SmartRest documentation as this is the way this library interfaces with Cumulocity: https://cumulocity.com/guides/reference/smartrest-two/#quick-reference.

I hope this helps. If you need more information. Try to find me on LinkedIn and we can have a longer conversation.

Kind regards,

Misja Heuveling
